<?php

// autoload_52.php generated by xrstf/composer-php52

require_once dirname(__FILE__) . '/composer'.'/autoload_real_52.php';

return ComposerAutoloaderInitbd3f61b8782be7b7ee7672bc8a9c3e13::getLoader();
